# Generated by Django 4.1 on 2022-12-22 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intituto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreInstituto', models.CharField(max_length=50)),
            ],
        ),
    ]
